BUILDING.txt
CONTRIBUTING.md

I'm opening this PR for some review/help. There are a couple of references to SVN left in the documentation (MERGE.txt and BUILDING.txt) that I'm not sure how to adjust. Anyone have thoughts on that?

Update BUILDING and CONTRIBUTING docs after the svn->git migration.

---

java/org/apache/tomcat/util/buf/B2CConverter.java
java/org/apache/tomcat/util/buf/CharsetCache.java
test/org/apache/tomcat/util/buf/TestCharsetCache.java
test/org/apache/tomcat/util/buf/TestCharsetCachePerformance.java
webapps/docs/changelog.xml

Implement an alternative Charset caching strategy that does not load all
Charsets at Tomcat start. This reduces start time by ~30ms and does not,
based on the performance tests included in this commit, have a negative
impact on runtime look-ups.
It does require that the names of all supported Charsets are known to
Tomcat at compile time. The code has been tested with a range of JVMs
and a unit test is provided for testing new JVMs.

Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=63235

---

bin/catalina.sh

Current check for TTY availability in catalina.sh doesn't work if non-English locales are installed and activated. This fix uses `test` command instead of `tty` command.

Use test -t command to check if STDOUT is opened on a terminal

---

java/org/apache/catalina/Globals.java
java/org/apache/catalina/filters/RemoteIpFilter.java
java/org/apache/catalina/valves/RemoteIpValve.java
test/org/apache/catalina/filters/TestRemoteIpFilter.java
test/org/apache/catalina/valves/TestRemoteIpValve.java
webapps/docs/changelog.xml

This is WIP, please review. I will squash, backport to 8.5.x (mark-forwarded-request/8.5.x) and merge into both branches. Should this land in 7.0.x too?

BZ 63556: Mark request as forwarded in RemoteIpValve/RemoteIpFilter

---

java/org/apache/catalina/authenticator/AuthenticatorBase.java
test/org/apache/catalina/authenticator/TestAuthInfoResponseHeaders.java
webapps/docs/changelog.xml
webapps/docs/config/valve.xml

Two issues:
* I have opted not to make the header names configurable to reduce complexity in the first place. This can be done if someone really requests it.
* I did not document the flag for the `SSLAuthenticator` because this happens before HTTP on the gateway, thus the gateway has the remote_user already and will forward the cert to the Tomcat instance.
If approved, I'll port back to 8.5.x and 7.0.x

BZ 62496: Add possibility write remote user/auth type to response header

---

java/org/apache/catalina/core/StandardWrapper.java
java/org/apache/catalina/realm/RealmBase.java
test/org/apache/catalina/core/TestStandardWrapper.java
test/org/apache/catalina/realm/TestRealmBase.java
webapps/docs/changelog.xml

Please have also an eye on the test. It passes as expected and it fails when I modify it, but I am not certain whether I have build the test they way it should be done.
If all is fine, I'll backport to 8.5.x and 7.0.x as long as the APIs are available.

BZ 63636: Context#findRoleMapping() never called in RealmBase#hasRole()

---

res/tomcat-maven/Dockerfile

The base image (openjdk:8-jre-alpine) already provides that folder.

Fix '/opt already exists' build error

---

webapps/docs/cluster-howto.xml

Was reading the documentation about session clustering and found some minor typographical issues.  Felt that they were small enough that rather than reporting by email, could just submit a patch. Hope this is okay!

spelling and formatting corrections for cluster-howto

---

java/javax/servlet/GenericServlet.java
java/org/apache/catalina/filters/AddDefaultCharsetFilter.java
java/org/apache/jasper/JspCompilationContext.java
java/org/apache/jasper/compiler/Generator.java
java/org/apache/tomcat/util/buf/CharChunk.java
java/org/apache/tomcat/util/security/ConcurrentMessageDigest.java

Hello, we're developing an automated system that detects inconsistent variable names in a large software project. Our system checks if each variable name is consistent with other variables in the project in its usage pattern, and proposes correct candidates if inconsistency is detected. This is a part of academic research that we hope to publish soon, but as a part of the evaluation, we applied our systems to your projects and got a few interesting results. We carefully reviewed our system output and manually created a patch to correct a few variable names. We would be delighted if this patch is found to be useful. If you have a question or suggestion regarding this patch, we'd happily answer. Thank you.

Made some variable names more consistent with the other parts.

---

.travis.yml
.travis/antTest.sh

Discussion at Tomcat dev@ mailing list: https://markmail.org/message/cjgake2g2372457v
Right after the discussion at dev@ I've created https://issues.apache.org/jira/browse/INFRA-19665 but so far there was one unsuccessful attempt by Infra team to setup BuildBot on the ARM64 VM. The main problem was that the VM is running on Ubuntu 18.04 and for some reason the Puppet setup didn't work on ARM64.
@gmcdonald said that soon he will attempt again with venv.
This PR provides an alternative by using TravisCI ARM64 nodes. 
It tests **only** on ARM64. We could enable AMD64 too later if needed.
It builds APR from its `trunk`, Tomcat-Native from `master` and Tomcat itself from the current branch (`master` for now, but if accepted I'd like to backport this to `9.x` and probably to `8.5.x`). So, this …

Test Tomcat on ARM64 at TravisCI

---

java/org/apache/tomcat/util/net/openssl/LocalStrings.properties
java/org/apache/tomcat/util/net/openssl/OpenSSLEngine.java

Per the [javadocs for `SSLEngine`](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngine.html#setEnableSessionCreation-boolean-), `setEnableSessionCreation` controls
whether or not new sessions are allowed to be created, or whether this
`SSLEngine` is restricted to resuming existing sessions. The default is
`true`, i.e., allow new sessions to be created. Because the OpenSSL
`SSLEngine` implementation does not limit the creation of new sessions,
`getEnableSessionCreation` should always return `true`, not `false`, and the
set operation should only yield an exception when the parameter is
false.
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
---
I haven't looked for any existing BZs discussing this topic; the code also appears unused within Tomcat so this is mostly an …

Fix semantics of get and set EnableSessionCreation

---

build.xml

As is, compiling with JDK9+ produces bytecode that can't run on older JVMs.

Set 'release' parameter for main compile target

---

java/org/apache/catalina/startup/Bootstrap.java

This is a very small commit that corrects a typo in the message of the
exception thrown when a quote character is used in path representing a
repository.

Fix typo in exception message about quote character in repository path

---

java/org/apache/catalina/startup/Bootstrap.java

The goal of this enhancement is to improve the regular expression used
for searching class loader repositories when bootstrapping Catalina.
With the Java regular expression engine which is regex-directed, we
gain in performance by using the negated character class [^\"]* rather
than the lazy quantifier .*? in the regular expression used for
searching class loader repositories when bootstrapping Catalina.

Improve Catalina class loader repositories regular expression

---

java/jakarta/el/LambdaExpression.java
java/jakarta/servlet/ServletSecurityElement.java
java/org/apache/catalina/connector/Request.java
java/org/apache/catalina/core/ApplicationContext.java
java/org/apache/catalina/core/AsyncContextImpl.java
java/org/apache/catalina/ha/context/ReplicatedContext.java
java/org/apache/catalina/manager/HTMLManagerServlet.java
java/org/apache/catalina/servlets/CGIServlet.java
java/org/apache/catalina/session/ManagerBase.java
java/org/apache/catalina/session/PersistentManagerBase.java
java/org/apache/catalina/session/StandardSession.java
java/org/apache/catalina/startup/HostConfig.java
java/org/apache/coyote/http11/AbstractHttp11Protocol.java
java/org/apache/coyote/http2/HPackHuffman.java
java/org/apache/coyote/http2/Http2UpgradeHandler.java
java/org/apache/jasper/compiler/TagLibraryInfoImpl.java
java/org/apache/tomcat/buildutil/MimeTypeMappings.java
java/org/apache/tomcat/util/net/AbstractJsseEndpoint.java
java/org/apache/tomcat/util/net/SSLUtilBase.java
java/org/apache/tomcat/util/net/openssl/OpenSSLContext.java
java/org/apache/tomcat/util/net/openssl/ciphers/Cipher.java
java/org/apache/tomcat/websocket/BackgroundProcessManager.java
test/org/apache/catalina/servlets/ServletOptionsBaseTest.java
test/org/apache/catalina/startup/TestTomcatNoServer.java
test/org/apache/catalina/valves/TestRemoteIpValve.java
test/org/apache/tomcat/util/buf/TestCharsetCache.java
test/org/apache/tomcat/util/descriptor/web/TestWebXmlOrdering.java
test/org/apache/tomcat/util/net/openssl/ciphers/TestCipher.java

This allows collections like ArrayList and HashSet to initialize their backing arrays
with the correct size.

Use parameterized collection constructors where possible

---

.travis.yml

As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.
Changes:
* Added s390x to build matrix
* Removed explicit steps to download java as they were redundant since using jdk tag from travis already provides expected java in the environment.

Add s390x Travis support

---

res/ide-support/idea/ant.xml
res/ide-support/idea/codeStyles/Project.xml
res/ide-support/idea/codeStyles/codeStyleConfig.xml
res/ide-support/idea/copyright/Tomcat.xml
res/ide-support/idea/copyright/profiles_settings.xml
res/ide-support/idea/externalDependencies.xml
res/ide-support/idea/inspectionProfiles/Project_Default.xml

This change makes IntelliJ IDEA ~and other IDE's~ aware of some of the coding standards of the Tomcat project.
~The .editorconfig file (and the rules therein) will be automatically used by the Editors listed here: https://editorconfig.org/#download~
The files in the .idea folder are for IntellIJ IDEA only. I deliberately put them directly there (and not in `res/ide-support/idea`) so no manual setup is neccessary for them to take effect.

Improve IDE support for IntelliJ IDEA

---

conf/web.xml
java/org/apache/catalina/filters/ExpiresFilter.java
webapps/docs/config/filter.xml
webapps/docs/ssi-howto.xml
webapps/docs/ssl-howto.xml
webapps/examples/websocket/chat.xhtml
webapps/examples/websocket/drawboard.xhtml
webapps/examples/websocket/echo.xhtml
webapps/examples/websocket/snake.xhtml

Changes were:
- `javascript` to `JavaScript`
- `Javascript` to `JavaScript`

Fix case of JavaScript.

---

java/org/apache/tomcat/websocket/server/WsHandshakeRequest.java

requests with scheme "wss" or "ws", as outlined in [RFC 6455 section 11.1](https://tools.ietf.org/html/rfc6455#section-11.1), will cause an `IllegalArgumentException` with message "wsHandshakeRequest.unknownScheme" without this change.
this fixes a regression from e09e6b04e41d3dae27fcfe060e6f8f89f1c0d6b5 / BZ 62731

support schemes "wss" and "ws" in WsHandshakeRequest.buildRequestUri()

---

java/org/apache/catalina/connector/CoyotePrincipal.java
java/org/apache/catalina/core/StandardThreadExecutor.java
java/org/apache/catalina/tribes/UniqueId.java
java/org/apache/juli/VerbatimFormatter.java
java/org/apache/tomcat/dbcp/dbcp2/datasources/CPDSConnectionFactory.java
java/org/apache/tomcat/dbcp/dbcp2/datasources/InstanceKeyDataSource.java
java/org/apache/tomcat/util/descriptor/web/ContextTransaction.java
java/org/apache/tomcat/util/digester/SetPropertiesRule.java
java/org/apache/tomcat/util/http/fileupload/FileUploadBase.java
webapps/examples/WEB-INF/classes/async/Stockticker.java
webapps/examples/WEB-INF/classes/filters/ExampleFilter.java

Do not use StringBuilder when String concatenation is just fine.
Append char instead of String when possible.
Fix the toString of ExampleFilter

Simplify some #toString() methods

---

java/org/apache/tomcat/util/IntrospectionUtils.java
test/org/apache/tomcat/util/TestIntrospectionUtils.java

Allow properties substitutions like:
my.http.port=8081
tomcat.http.port=${my.http.port}
It is related to https://issues.redhat.com/browse/JWS-973 and https://bz.apache.org/bugzilla/show_bug.cgi?id=62160

Allow recursive substitution of properties.

---

java/org/apache/catalina/startup/LocalStrings_ja.properties

versionLoggerListener.* properties are consistently indented with spaces.
Japanese translations should follow English ones.

Fix indentation of versionLoggerListener.*

---

java/org/apache/catalina/ant/jmx/JMXAccessorCondition.java
java/org/apache/catalina/ant/jmx/JMXAccessorCreateTask.java
java/org/apache/catalina/ant/jmx/JMXAccessorTask.java
java/org/apache/catalina/core/ApplicationContext.java
java/org/apache/catalina/core/StandardContext.java
java/org/apache/catalina/core/StandardEngine.java
java/org/apache/catalina/filters/WebdavFixFilter.java
java/org/apache/catalina/ha/backend/TcpSender.java
java/org/apache/catalina/ha/session/JvmRouteBinderValve.java
java/org/apache/catalina/manager/HTMLManagerServlet.java
java/org/apache/catalina/manager/ManagerServlet.java
java/org/apache/catalina/manager/host/HostManagerServlet.java
java/org/apache/catalina/realm/RealmBase.java
java/org/apache/catalina/servlets/CGIServlet.java
java/org/apache/catalina/session/JDBCStore.java
java/org/apache/catalina/storeconfig/StoreRegistry.java
java/org/apache/catalina/util/ContextName.java
java/org/apache/el/MethodExpressionImpl.java
java/org/apache/el/MethodExpressionLiteral.java
java/org/apache/el/ValueExpressionImpl.java
java/org/apache/el/ValueExpressionLiteral.java
java/org/apache/el/lang/ELSupport.java
java/org/apache/el/lang/FunctionMapperImpl.java
java/org/apache/el/util/ReflectionUtil.java
java/org/apache/jasper/JspC.java
java/org/apache/jasper/compiler/Generator.java
java/org/apache/jasper/compiler/Validator.java
java/org/apache/tomcat/util/digester/SetPropertiesRule.java
java/org/apache/tomcat/util/net/SSLUtilBase.java
java/org/apache/tomcat/websocket/WsWebSocketContainer.java

Blog post with microbenchmarks: https://medium.com/javarevisited/micro-optimizations-in-java-string-equals-22be19fd8416
Proposal for similar change in JDK: https://github.com/openjdk/jdk/pull/29

Micro optimization: replace "".equals(a) with a.isEmpty()

---

java/jakarta/el/ELContext.java

in case of a JSF view, this methods are called quite often and creates ArrayList and ArrayList$Itr instances, also if no listener is added.
This reduces the created objects of a simple view demo view (-54k objects in 400 requests)
We could even improve it a bit by using a index-loop, which also avoids a ArrayList$Itr instance, if listeners are available. Not sure if Tomcat maintainers likes such changes.
It would also be great if you could port it to older branches

[perf] Lazy init ELContext#listeners to avoid unnecessary ArrayList and ArrayList$Itr

---

java/org/apache/catalina/connector/Request.java
java/org/apache/catalina/util/TLSUtil.java
java/org/apache/coyote/AbstractProcessor.java
java/org/apache/tomcat/util/buf/HexUtils.java
java/org/apache/tomcat/util/net/AprSSLSupport.java
java/org/apache/tomcat/util/net/LocalStrings.properties
java/org/apache/tomcat/util/net/Nio2Endpoint.java
java/org/apache/tomcat/util/net/NioEndpoint.java
java/org/apache/tomcat/util/net/SSLImplementation.java
java/org/apache/tomcat/util/net/SSLSupport.java
java/org/apache/tomcat/util/net/SecureNio2Channel.java
java/org/apache/tomcat/util/net/SecureNioChannel.java
java/org/apache/tomcat/util/net/TLSClientHelloExtractor.java
java/org/apache/tomcat/util/net/jsse/JSSEImplementation.java
java/org/apache/tomcat/util/net/jsse/JSSESupport.java
java/org/apache/tomcat/util/net/openssl/OpenSSLImplementation.java
webapps/docs/changelog.xml
webapps/docs/config/http.xml

https://bz.apache.org/bugzilla/show_bug.cgi?id=64110
I'm providing a PR for this one as the additional attributes to add some additional overhead. The overhead is limited to keeping two lists of strings: one of requested protocol names and one of requested cipher names. In both cases the names are already in memory so the footprint will be limited to the lists and array of object references. The exceptions are the relatively new GREASE values (see RFC 8701). I don't think they'll cause too much overhead (and there are ways to workaround that if they do - namely do exactly what RFC 8701 doesn't want us to do and enumerate them).

Fix BZ 64110 - request attr for requested ciphers and protocols

---

java/org/apache/catalina/valves/AbstractAccessLogValve.java
test/org/apache/catalina/valves/TestAbstractAccessLogValveEscape.java
webapps/docs/changelog.xml
webapps/docs/config/valve.xml

https://bz.apache.org/bugzilla/show_bug.cgi?id=60781
It isn't quite as simple just escape where httpd does as httpd and Tomcat support slightly different things and validate at different points. See the code comments.
I was concerned about performance but after checking which elements need escaping (see code comments) I think this should be OK. I used Felix's original patch as my starting point but used chars rather than bytes and appended directly to the buffer. Give the potential performance issues, doing this as a PR.

Fix BZ 60781 Escape access log output where httpd does

---

java/org/apache/catalina/connector/Request.java
java/org/apache/catalina/valves/AbstractAccessLogValve.java
java/org/apache/catalina/valves/LocalStrings.properties
java/org/apache/catalina/valves/RemoteAddrValve.java
java/org/apache/catalina/valves/RemoteCIDRValve.java
java/org/apache/catalina/valves/RequestFilterValve.java
java/org/apache/coyote/AbstractProcessor.java
java/org/apache/coyote/ActionCode.java
java/org/apache/coyote/Constants.java
java/org/apache/coyote/Request.java
java/org/apache/coyote/RequestInfo.java
java/org/apache/coyote/ajp/AjpProcessor.java
test/org/apache/catalina/valves/TestRequestFilterValve.java
webapps/docs/changelog.xml
webapps/docs/config/valve.xml

It contains the IP address of the direct connection peer.
If a reverse proxy sits in front of Tomcat and the protocol
used is AJP or HTTP in combination with the RemoteIp(Valve|Filter),
the peer address might differ from the remoteAddress.
The latter then contains the address of the client in front of the
reverse proxy, not the address of the proxy itself.
Support for the peer address has been added to the
RemoteAddrValve and RemoteCIDRValve with the new attribute
"usePeerAddress". This can be used to restrict access
to Tomcat bsed on the reverse proxy IP address, which is especially
useful to harden access to AJP connecrtors.
The peer address can also be logged in the access log
using the new %{peer}a syntax.

Add peerAddress to coyote request

---

java/org/apache/catalina/valves/AbstractAccessLogValve.java
webapps/docs/config/valve.xml

In the current and older tomcat docs the distinction between capital i and l is not evident with use of open sans font[1]. This is common typography issue which could be avoided with font that have distinctions in commonly confused characters similar to http's log format doc.[2] 
~~~
%l - Remote logical username from identd (always returns '-')
%I - Current request thread name (can compare later with stacktraces)
~~~
[1] https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Introduction 
[2] http://httpd.apache.org/docs/2.4/mod/mod_log_config.html#formats

[65022] Use of font with distinct lowercase l , capital I (i) and one 1 tomcat access log pattern definition

---

java/org/apache/catalina/ha/deploy/FarmWarDeployer.java
java/org/apache/catalina/manager/HTMLManagerServlet.java
java/org/apache/catalina/manager/ManagerServlet.java
java/org/apache/catalina/mbeans/LocalStrings.properties
java/org/apache/catalina/mbeans/MBeanFactory.java
java/org/apache/catalina/startup/HostConfig.java
java/org/apache/catalina/startup/mbeans-descriptors.xml
webapps/docs/changelog.xml

As per this thread:
https://tomcat.markmail.org/thread/33xw2jkp4fmcpl7o
Details in the commit messages but the short version was "serviced" wasn't doing what was intended in all cases. Improving serviced enabled the Manager app to perform deploy different web apps in parallel.
This is a fairly large change so submitting as a PR for review before I commit it.

Allow the Manager application to deploy applications in parallel

---

java/org/apache/coyote/http11/Http11InputBuffer.java
test/org/apache/coyote/http11/TestHttp11InputBuffer.java
test/org/apache/coyote/http11/TestHttp11InputBufferCRLF.java
webapps/docs/changelog.xml

Potential fix for https://bz.apache.org/bugzilla/show_bug.cgi?id=65272
Needs careful review, hence using a PR.
If you spot any potential ways an invalid HTTP request line or header could be:
- accepted as valid
- rejected later than necessary
- rejected for the 'wrong' reason
or any other potential parsing error please report it. For bonus points provide a test case that demonstrates the issue.
As always, anything that might have security implications for a current Tomcat release should go to security@a.o rather than here.

Fix BZ 65272. Restore the use of LF as an HTTP line terminator

---

res/bnd/catalina.jar.tmp.bnd

References to org.apache.catalina.ssi are still contained in catalina.jar after it was moved to a separate catalina-ssi.jar. It should be cleaned up.

Remove catalina ssi from catalina.jar.tmp.bnd file

---

java/org/apache/tomcat/util/http/MimeHeaders.java
webapps/docs/changelog.xml

Minor improvement to show header name/value in IDE while debugging.  Without it you get an array of object that looks like this:
Most IDEs like Intellij will show the toString value automatically beside the instance.  Most other objects in coyote Request have a toString already and show up quite nicely:

MimeHeader.toString to speed up debugging in IDEs

---

java/org/apache/catalina/loader/WebappClassLoaderBase.java
test/org/apache/catalina/loader/TestWebappClassLoader.java

Some users mistakenly add `jakarta.annotation-api` to their applications, which prevents Tomcat from finding `@Resource` and similar annotations on the servlets. See [this Stack Overflow question](https://stackoverflow.com/q/69249988/11748454) for example.
To prevent this "jakarta.annotation" should also be always loaded from the common classloader.

Load "jakarta.annotation.*" classes from common classloader

---

java/org/apache/tomcat/util/http/FastHttpDateFormat.java

When you set the system time to a newer date by accident, then you reset system time to an older date, but the HTTP header response date field cannot be changed. It is still the newer date.

Allow http response date field set to older date

---

java/org/apache/catalina/connector/Response.java

If no ROOT context is defined, the context may be null in special cases, e.g. RewriteValve may use Response#sendRedirect() without any application context associated.
In this case, the Tomcat behaviors for the context attributes useRelativeRedirects and sendRedirectBody are assumed, but without considering org.apache.catalina.STRICT_SERVLET_COMPLIANCE.

Fix Response#sendRedirect() if no request context exists.

---

java/org/apache/catalina/realm/X509SubjectDnRetriever.java

According to java spec, getSubjectDN() should not be used:
"denigrated, replaced by getSubjectX500Principal(). This method returns the subject as an implementation specific Principal object, which should not be relied upon by portable code."
Not sure if my proposed change is correct, at least it is probably not compatible for all use cases.

replace deprecated getSubjectDN()

---

java/org/apache/catalina/core/StandardThreadExecutor.java
java/org/apache/catalina/core/mbeans-descriptors.xml
webapps/docs/config/executor.xml

I found that in the constructor of the ThreadPoolExecutor, all core threads are started by default, so in the StandardThreadExecutor, prestartminSpareThreads becomes meaningless.But I don't know if it's right to just remove.

Remove the prestartminSpareThreads field from StandardThreadExecutor

---

res/ide-support/idea/tomcat.iml

when i run idea with the main branch of the tomcat,i found the version of  easymock  in the tomcat/res/ide-support/idea/tomcat.iml should be sync update.

easymock version change from 4.2 to 4.3

---

java/org/apache/juli/ClassLoaderLogManager.java
test/org/apache/juli/TestClassLoaderLogManager.java

Since Java 8 the default level of a root logger is no longer set in the
constructor. This PR sets the level to INFO (LogManager's default) if it
is absent.
This patch should work on all the branches.

[Bug 66184] Ensure that all root loggers have a level or parent

---

java/org/apache/coyote/http11/Http11Processor.java
test/org/apache/coyote/http11/TestHttp11Processor.java

Fixing a bug where a connection would be kept alive without swallowing the input from the request stream.
When a request comes in with a 100 Continue expectation, and the server immediately responds with a 200 status without reading the request body at all, the next request on the connection will fail because Tomcat cannot parse the HTTP verb. The first request left Http11Processor in a state where it kept the connection alive but did not discard the request body, thus reading the next request began at the wrong place in the stream.
The new unit test replicates the issue and is addressed by the code changes to keep the keepAlive and input buffer swallow state in sync with each other.

Http11Processor's keep alive state and input buffer's swallow state must be synchronized

---

java/org/apache/juli/FileHandler.java

The default formatter was changed [here](https://github.com/apache/tomcat/commit/7d0408eb47c52376cf210cc4b8d897d1bffac947#diff-e0d7b86da38bd411282a14bd82e8cc517ff64f68fc3c882647e5a3e0ed736840R335).

Fix Javadoc to reflect the change in default formatter

---

res/graal/tomcat-embed-core/native-image/tomcat-reflection.json
res/graal/tomcat-embed-el/native-image/tomcat-resource.json

This pull request fixes regressions in the Tomcat 10.1 native support compared to Tomcat 10.0.
It brings back required reflection metadata on `AbstractProtocol` and `AbstractHttp11Protocol` lost after `Http11AprProtocol` removal, and rename resource metadata from `org.apache.el.Messages` to `org.apache.el.LocalStrings`.

Native metadata update for Tomcat 10.1

---

webapps/docs/changelog.xml

https://bz.apache.org/bugzilla/show_bug.cgi?id=66029 poi 5.0 generated xlsx file RUN TO EMAIL APPENDS .TXT TO OUTPUT
https://bz.apache.org/bugzilla/show_bug.cgi?id=66209 CPU regression when classpath Bloom filters are active

fix issue id in changelog

---

modules/jdbc-pool/build.xml

Fixes [Bug 66346](https://bz.apache.org/bugzilla/show_bug.cgi?id=66346). Only the first change is required to fix the timestamps in `tomcat-jdbc-src.jar`, but this seemed a good time to fix the timestamps in the other two JAR files as well (`tomcat-jdbc-test.jar` and `tomcat-jdbc-test-src.jar`).
Can someone let me know how I might test the building of those two test JAR files? I couldn't figure out which Ant target to use for building and comparing them. I did run the unit test cases, which were successful:
```console
$ ant test
...
[concat] Testsuites with failed tests:
test:
BUILD SUCCESSFUL
Total time: 110 minutes 45 seconds
```

Allow reproducible builds of all JDBC JAR files

---

modules/stuffed/tomcat-resource.json
res/graal/tomcat-embed-core/native-image/tomcat-resource.json
res/graal/tomcat-embed-el/native-image/tomcat-resource.json
res/graal/tomcat-embed-jasper/native-image/tomcat-resource.json
res/graal/tomcat-embed-programmatic/native-image/tomcat-resource.json
res/graal/tomcat-embed-websocket/native-image/tomcat-resource.json

This commit updates the native resources hints in order to avoid classpath wide inclusion of resources.
@markt-asf @mhalbritter Please check I did not make any mistake.

Refine native resources metadata

---

res/ide-support/eclipse/eclipse.classpath
res/ide-support/idea/tomcat.iml
res/ide-support/netbeans/nb-tomcat-build.properties
res/ide-support/netbeans/project.xml

There seems to be a difference in the dependency versions in the build.properties file and the IDE config files, which I have corrected.

Update objenesis and unboundid versions for IDE configs

---

java/org/apache/catalina/startup/ClassLoaderFactory.java
java/org/apache/catalina/util/ContextName.java
java/org/apache/jasper/compiler/SmapUtil.java
java/org/apache/tomcat/buildutil/translate/Utils.java
test/jakarta/el/TestImportHandlerStandardPackages.java
test/org/apache/juli/TestFileHandler.java
test/org/apache/tomcat/util/http/parser/TestMediaType.java
test/org/apache/tomcat/util/net/openssl/ciphers/TesterOpenSSL.java

replaceAll("ABC", "") is non Pattern method and therefore must be replaced to simple fast replace()
A proofs of changes: https://gist.github.com/tbw777/8a6ef60af21487c5faec67037099fd0b

Speedup by removing non pattern replaceAll with constant arg

---

java/org/apache/catalina/startup/VersionLoggerListener.java
java/org/apache/catalina/storeconfig/ConnectorStoreAppender.java
java/org/apache/catalina/storeconfig/StandardContextSF.java
java/org/apache/catalina/storeconfig/StoreContextAppender.java
java/org/apache/catalina/storeconfig/StoreFileMover.java
java/org/apache/tomcat/jni/Library.java
test/org/apache/catalina/startup/LoggingBaseTest.java
test/org/apache/tomcat/util/file/TestConfigFileLoader.java

We seem to have some duplication, e.g. `o.a.c.Globals.CATALINA_HOME_PROP` which is set from `o.a.c.startup.Constants.CATALINA_HOME_PROP`.
Do we need `o.a.c.startup.Constants` to be separate for some reason, e.g. for packaging different JARs, or can we consolidate the code and use just `o.a.c.Globals` instead?
The current PR does not modify that.  It only replaces the literal strings `"catalina.home"` and `"catalina.base"` with constants from `Globals`, or in the `o.a.c.startup` package with `Constants`.
I'm opening the PR so there are more eyes on it before I make the change, and will merge it after some reasonable time passes if no one raises any issues with it.

Use available constants

---

java/org/apache/catalina/core/LocalStrings.properties
java/org/apache/catalina/core/StandardContext.java
webapps/docs/changelog.xml

Give it its own log message instead of re-using the one from fireRequestInitEvent.

Fix Bug 66543 -  Wrong log message used in StandardContext#fireRequestDestroyEvent

---

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/PoolProperties.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/pool/PoolPropertiesTest.java

Fixes minor annoyance when analyzing log files

Ensure brackets are closed in PoolProperties.toString

---

java/org/apache/tomcat/websocket/AsyncChannelGroupUtil.java

From https://bz.apache.org/bugzilla/show_bug.cgi?id=66581 
Currently the ExecutorService used for this is as such:
ExecutorService executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, Long.MAX_VALUE, TimeUnit.MILLISECONDS, new SynchronousQueue<>(), new AsyncIOThreadFactory());
This means that the threads never terminate and are spawned whenever a thread is not available, which for a server under a spike of load spawns many threads which never exit, consuming system resources indefinitely.
I would suggest that a saner idle timeout than Long.MAX_VALUE should be used, such as 60 seconds, unless there is a good reason I am unaware of as to why such threads should never die.

Don't allow idle threads to live forever

---

java/org/apache/catalina/filters/LocalStrings.properties
java/org/apache/catalina/filters/RateLimitFilter.java
java/org/apache/catalina/util/TimeBucketCounter.java
test/org/apache/catalina/filters/TestRateLimitFilter.java
test/org/apache/catalina/util/TestTimeBucketCounter.java
webapps/docs/config/filter.xml

This patch adds a RateLimitFilter based on the discussion in the Dev mailing list at [1] with more features to be added later
[1] https://lists.apache.org/thread/0gt1kyjs86g9oqxofdgm0zbrb14lzgj6

Added RateLimitFilter

---

java/org/apache/catalina/core/ContextNamingInfoListener.java
java/org/apache/catalina/core/LocalStrings.properties
test/org/apache/catalina/core/TestContextNamingInfoListener.java
webapps/docs/changelog.xml
webapps/docs/config/listeners.xml

A listener which creates context naming information environment entries.
This is something which I have been using for years at work. It suited for all components which dot not have access to Tomcat internals, but need context information, e.g., 
In Logback:
```xml
<configuration>
<insertFromJNDI env-entry-name="java:comp/env/context/baseName" as="contextName" />
<contextName>${contextName}</contextName>
...
</configuration>
```
In Spring:
```xml
<beans:bean id="contextSource" class="org.springframework.ldap.pool2.factory.PooledContextSource">
<beans:constructor-arg>
<beans:bean class="org.springframework.ldap.pool2.factory.PoolConfig" p:testOnBorrow="true"
p:minEvictableIdleTimeMillis="300000" p:maxWaitMillis="5000"
p:jmxNameBase="org.apache.commons.pool2:context=${context/name},type=Gene …
```

Add ContextNamingInfoListener

---

res/bnd/catalina-tribes.jar.tmp.bnd

Since package org.apache.catalina.tribes.transport.bio was deprecated in tomcat 10, https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/catalina/tribes/transport/bio/package-summary.html , references to it in catalina-tribes.jar should be removed.

Remove transport.bio from catalina-tribes.jar.tmp.bnd

---

java/org/apache/catalina/session/StandardSession.java

Misleading warning message is logged in the following scenario:
- When persistAuthentication="true".
When a user is logged-out of the system and redirected to the login page, they are given a session whose principle object is null.
- If in that period the tomcat server is restarted, the doWriteObject from org.apache.catalina.session.StandardSession is called where on line 1489 it tries to check if the sessionPrincipal is serializable, but does not check if it is null before that - (https://github.com/apache/tomcat/blob/10.1.x/java/org/apache/catalina/session/StandardSession.java#L1489 ).
- If the principal is null (like in the above-described scenario) - then the manager logs a warning message saying it cannot serialize the principal for the session. This is somewhat misleading as there …

Catalina [StandardSession] bug id=66680 (misleading warn about non-serializable principal)

---

java/org/apache/catalina/realm/JNDIRealm.java
webapps/docs/changelog.xml

In Java 8 and up to 17 a closed connection is signaled with a NamingException and not a CommunicationException ora ServiceUnavailableException.  Such a condition should lead to re-opening the LDAP connection.

Catch NamingException instead of specialized sub-classes

---

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/ConnectionPool.java

In Tomcat JDBC module, I reckon PoolCleaner cleans the idle connections in two ways
- checkIdle
- testAllIdle
`releasedIdleCount` is incremented when released from `checkIdle` but not from `testAllIdle`. Is it part of the design? If so, why is it not counted?
IMO, the counter should be incremented in `testAllIdle` too. This PR includes this change.

Increment ReleaseIdle Counter when testAllIdle releases them

---

java/org/apache/tomcat/util/net/SSLUtilBase.java

When using nmap --script ssl-enum-ciphers -p port host
the ciphers proposed are often a small subset of the expect ones.
A warning helps to see what is rejected.

Warn when non default ciphers are removed because the engine rejects them.

---

java/org/apache/catalina/connector/Request.java

This Pull Request aims to reduce code duplication in the `getSession` method of the `Request` class.
The refactoring closely follows the structure and principles used in the `reset` method of `java.org.apache.catalina.connector.OutputBuffer`:
```java
public void reset() {
reset(false);
}
public void reset(boolean resetWriterStreamFlags) {
clear(bb);
clear(cb);
bytesWritten = 0;
charsWritten = 0;
if (resetWriterStreamFlags) {
if (conv != null) {
conv.recycle();
}
conv = null;
}
initial = true;
}
```

Refactor 'getSession' Method in 'Request' Class to Eliminate Code Redundancy

---

java/org/apache/catalina/connector/RequestFacade.java

In the current implementation of the `getSession` method in the `RequestFacade` class, the checkFacade logic was redundantly executed twice.
I improved this by eliminating the redundancy.

Eliminating duplicate execution of checkFacade logic

---

java/org/apache/catalina/connector/Request.java

Hello,
I have fixed a typo in the Tomcat codebase by changing "CookiePreocessor" to "CookieProcessor" for better code clarity and correctness.

Fix a comment typo

---

java/org/apache/catalina/util/SessionConfig.java

Optimization when call getSessionCookieName & getSessionUriParamName
Existing code calls getConfiguredSessionCookieName even if the context is empty.
In getConfiguredSessionCookieName, only act to get the session cookie if the context is non-null.
I think it's possible to avoid calling getConfiguredSessionCookieName and use Default defined by spec if context is null.
It's a small optimisation, but I think it saves us one less function call.
Additionally, modified getConfiguredSessionCookieName to not require a null check on its result.
One fewer comparison operation if context is non-null. and I think it makes the code a little easier to understand for the remaining priority comments.

Optimize when call getSessionCookieName & getSessionUriParamName

---

java/org/apache/coyote/http11/Http11Processor.java

It can be confusing to read the code because the part that checks for HTTP compression and the part that applies the filter are separated from each other
I've placed them back-to-back to improve readability.

Relocate the useCompression check and apply parts back to back

---

java/org/apache/tomcat/util/net/Nio2Channel.java
java/org/apache/tomcat/util/net/NioChannel.java

NioChannel's toString() causes NioEndpoint's setSocketOptions method to throw a NullPointerException in some scenarios (e.g. idea breakpoint debugging).

Fix NioChannel's toString() throwing NullPointerException in some cases

---

webapps/docs/config/http.xml

Trivial wording fix for config docs.
_(Unfortunately goes all the way back to `9.0.x` and `8.5.x`)_

Fix HTTP/2 support wording in HTTP docs

---

java/org/apache/catalina/connector/Connector.java
java/org/apache/catalina/filters/ExpiresFilter.java
java/org/apache/catalina/filters/RemoteCIDRFilter.java
java/org/apache/catalina/filters/RemoteIpFilter.java
java/org/apache/catalina/realm/JNDIRealm.java
java/org/apache/catalina/util/NetMaskSet.java
java/org/apache/catalina/valves/RemoteCIDRValve.java
java/org/apache/catalina/valves/RemoteIpValve.java
java/org/apache/tomcat/util/buf/StringUtils.java
test/org/apache/catalina/filters/TestRemoteIpFilter.java
test/org/apache/catalina/valves/TestRemoteIpValve.java

There was repeated code in various places in the source tree to spit simple comma-separated strings using the regular expression pattern `\s*,\s*`. This PR gathers those together into a single utility method and re-implements that method without using a regular expression which improves performance.
Given that this method is often used on request headers, the aggregate performance improvement over many requests is measurable especially for long strings, strings with many components, etc.
Implementation note: there is a subtle change to the behavior of this utility method relative to the original: this _new_ method results in the first and last strings being "trimmed" of whitespace while the _old_ implementation would have preserved leading whitespace in the first string value returned and …

Unify comma-separated-value code and optimize the implementation

---

webapps/docs/changelog.xml

Hey,
we figured, that atm the changelog.xml can not be parsed
```python
>>> import requests
>>> import xmltodict
>>> xml = requests.get(f"https://raw.githubusercontent.com/apache/tomcat/10.1.x/webapps/docs/changelog.xml",timeout=1800).text
>>> mydict = xmltodict.parse(xml)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3/dist-packages/xmltodict.py", line 378, in parse
parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 107, column 47
>>> xml = xml.replace('"Tomcat 10.1.25 (schultz)','"Tomcat 10.1.25 (schultz)"')
>>> mydict = xmltodict.parse(xml)
```
due to the missing quotation mark.
Thanks for all the work, all the years!
BR
Christian

adds missing quotation mark - makes changelog.xml parsable again

---

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/StatementFacade.java
modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/interceptor/AbstractCreateStatementInterceptor.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/ProxiedResultSetTest.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/ProxiedStatementTest.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/driver/ResultSet.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/driver/Statement.java

The tomcat-jdbc connection pool creates reflective proxies around Connections, Statements, and ResultSets to allow interception of 'close' calls, and consistency of traversing the link back from a child element to its parent - e.g. Statement to Connection. However, the link from ResultSet to Statement does not intercept the call so a non-proxied Statement is returned, as well as the `equals` method not handling the comparison against a non-proxied class correctly. To overcome this, an invocation handler is being created for wrapping a ResultSet returned from any of the relevant Statement methods, with that invocation handler intercepting the `getStatement` call and returning the proxied creating statement. The `equals` checks have also been altered to handle non-proxied instances being …

Correctly Proxy Statement returned from ResultSet

---

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/StatementFacade.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/ProxiedStatementTest.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/driver/Connection.java
modules/jdbc-pool/src/test/java/org/apache/tomcat/jdbc/test/driver/Statement.java

When executing a wrapped statement, any resulting SQLException is wrapped in an InvocationTargetException by the reflective invocation, which is rethrown by the InvocationHandler as an
UndeclaredThrowableException. To ensure the expected SQLException is thrown, the invocation of the wrapped object is being moved into the existing try-catch block, thereby ensuring the InvocationTargetException is unwrapped and the underlying exception thrown by the handler.
https://bz.apache.org/bugzilla/show_bug.cgi?id=69255

Unwrap InvocationTargetException from underlying statement execution

---

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/pool/StatementFacade.java

When invoking a method on a proxied statement returns `null`, that statement's proxy should also return `null`.
In particular, `Statement#getResultSet` should not return a `ResultSetProxy` when the proxied statement returns `null`. Otherwise, that `ResultSet` proxy has a `null` delegate and calling methods on the proxy that lead to calling methods on the delegate could result in a `SqlException` with message "ResultSet closed."
We found this issue because our Spring + MyBatis application started throwing `SqlException`s when calling stored procedures after upgrading to Tomcat v. 10.1.28, whereas it didn't in version 10.1.26.
Looking in the MyBatis code, it checks if a `Statement`'s `ResultSet` is `null` or not. If it isn't—and it isn't when the `ResultSet` is proxied with a `null` …

Fix proxying null value result set

---

java/org/apache/tomcat/util/http/FastHttpDateFormat.java
test/org/apache/tomcat/util/http/TestFastHttpDateFormat.java
test/org/apache/tomcat/util/http/TesterFastHttpDateFormat.java

FastHttpDateFormat#getCurrentDate() returns same string for two different second datetime.
For following date:
1st:1726041009036, Wed, 11 Sep 2024 07:50:09 GMT
2nd:1726041009940, Wed, 11 Sep 2024 07:50:09 GMT
1st:1726041011501, Wed, 11 Sep 2024 07:50:11 GMT
***2nd:1726041012101, Wed, 11 Sep 2024 07:50:11 GMT*** --it is incorrect.
Fix: check whether cached date and current date are in same second.

fix bz #69316 FastHttpDateFormat - getCurrentDate() returns inaccurate result

---

test/org/apache/catalina/authenticator/TestFormAuthenticatorA.java

This Unit test makes sure that the expires and date headers are consistent and both use GMT, as per the bug report https://bz.apache.org/bugzilla/show_bug.cgi?id=62476

Unit test ensuring that the Expires and Date headers use GMT

---

webapps/docs/config/http.xml

Added default value for connectionUploadTimeout in the event that a value is not provided and disableUploadTimeout is set to false.

Adding connectionUploadTimeout default value to http.xml

---

webapps/docs/config/filter.xml

https://bz.apache.org/bugzilla/show_bug.cgi?id=69477
I have detected that the 'allowedInternalProxies' param name in the Remote IP Filter documentation here https://tomcat.apache.org/tomcat-11.0-doc/config/filter.html#Remote_IP_Filter is incorrect.
See correction in the first commit e716e7a2536c571e6bc8ddc5628133bb325e4ab8
I have also added some missing filter-mapping sections in some of the RemoteIpFilter examples
Thank you

BZ 69477: Wrong 'allowedInternalProxies' param name in the Remote IP Filter documentation 

---

java/org/apache/catalina/servlets/DefaultServlet.java
test/org/apache/catalina/servlets/TestDefaultServletRfc14.java

- Bug: incorrect partial content response to HEAD request with-Range-header
***Tomcat*** - 206:
```
C:\Users\chenjp>curl http://localhost:55263/index.html -i -H "Range: bytes=0-10" -I
HTTP/1.1 206
vary: accept-encoding
Accept-Ranges: bytes
```
***www.apache.org*** offcial site - 200: 
```
C:\Users\chenjp>curl https://www.apache.org -i -H "Range: bytes=0-10" -I
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 64483
```
- Bug: receives a partial content sc from a Not-accept-range server (DefaultServlet with init param useAcceptRanges=false)
```
C:\Users\chenjp>curl http://localhost:55463/index.html -i -H "Range: bytes=0-10"
HTTP/1.1 206
vary: accept-encoding
ETag: W/"957-1732881015126"
```
ChangeLog:
* per RFC 9110 - Section 14, currently GET is the only method.
* A server that turn …

fix incorrect partial content response to HEAD request with-Range-header, or from Not-accept-range server

---

java/org/apache/catalina/servlets/DefaultServlet.java
test/org/apache/catalina/servlets/TestDefaultServletRangeRequests.java

Request that ranges are not strictly in ascending order, indicates either a broken client or a deliberate denial-of-service attack.

Reject Range-Request if those ranges are not strictly in ascending order

---

webapps/docs/default-servlet.xml

Document of DefaultServlet - correct the referenced RFC spec number about partial PUT - a PUT with Content-Range Header.
The original text of ***RFC7231*** #4.3.4 (which is obsoleted by RFC9110): An origin server that allows PUT on a given target resource MUST send a 400 (Bad Request) response to a PUT request that contains a Content-Range header field

tiny doc adj

---

java/org/apache/catalina/servlets/DefaultServlet.java

comply [rfc 9110 Section 15.5.6.](https://httpwg.org/specs/rfc9110.html#status.405) 405 Method Not Allowed:
The origin server ***MUST*** generate an ***[Allow](https://httpwg.org/specs/rfc9110.html#field.allow)*** header field in a 405 response containing a list of the target resource's currently supported methods.
Personally, #802 may be an alternative choice.

for delete failure case, send Allow header at same time with sc  Method not allowed

---

java/org/apache/tomcat/util/http/MimeHeaders.java

This is to avoid having to convert from Bytes to String again for the same header.

Invoke toStringType instead of toString in MimeHeaders

---

java/org/apache/coyote/http2/Http2UpgradeHandler.java

Fix info-then-debug logging in `Http2UpgradeHandler` by making the `UserDataHelper` static. Otherwise the _lastInfoTime_ in `UserDataHelper` will be per HTTP2-connection, but it should be a global scoped timestamp.
This also makes it consistant with how `UserDataHelper` is used in `Cookie`.

Fix info-then-debug logging in Http2UpgradeHandler

---

java/org/apache/jasper/EmbeddedServletOptions.java
java/org/apache/jasper/JspC.java
java/org/apache/jasper/Options.java
java/org/apache/jasper/compiler/Generator.java
java/org/apache/jasper/runtime/JspRuntimeLibrary.java
test/jakarta/servlet/jsp/TesterPageContext.java
test/jakarta/servlet/jsp/TesterPageContextWithAttributes.java
test/org/apache/jasper/compiler/TestGenerator.java
test/org/apache/jasper/compiler/TestNonstandardTagPerformance.java
test/org/apache/jasper/runtime/TestJspRuntimeLibrary.java
test/webapp/WEB-INF/web.xml
test/webapp/jsp/generator/nonstandard/remove-01.jsp
test/webapp/jsp/generator/nonstandard/remove-02.jsp
test/webapp/jsp/generator/nonstandard/remove-03.jsp
test/webapp/jsp/generator/nonstandard/remove-04.jsp
test/webapp/jsp/generator/nonstandard/remove-05.jsp
test/webapp/jsp/generator/nonstandard/set-01.jsp
test/webapp/jsp/generator/nonstandard/set-02.jsp
test/webapp/jsp/generator/nonstandard/set-03.jsp
test/webapp/jsp/generator/nonstandard/set-04.jsp
test/webapp/jsp/generator/nonstandard/set-05.jsp
webapps/docs/changelog.xml

Enables optimized, non-standard behavior for the most common JSP tags, when configured to do so.
**Impact:** benchmark (included)shows 99% reduction in cpu, 100% reduction in object allocation
**Activation:** off by default, enabled via an init param to the JSP servlet, such as:
```
<init-param>
<param-name>useNonstandardTagOptimizations</param-name>
<param-value>c:set,c:remove</param-value>
</init-param>
```
**Example:**
Old code (standard): one method, two parameters, 10+ lines of code, one object allocated (and it's large!).
```
private boolean _jspx_meth_c_005fset_005f39(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f11, javax.servlet.jsp.PageContext _jspx_page_context)
throws java.lang.Throwable {
javax.servlet.jsp.PageContext pageContext = _jspx_page_context; …
```

Adding nonstandard support for c:set and c:remove

---

test/org/apache/catalina/servlets/TestWebdavServlet.java

add cases for allowSpecialPaths=true.

webdav testcase for special path

---

java/org/apache/catalina/valves/rewrite/RandomizedTextRewriteMap.java
test/conf/TesterRewriteMapB.txt

enable inline comment support for plain text rewrite map.
Per doc [rewritemap.html#txt](https://httpd.apache.org/docs/2.4/rewrite/rewritemap.html#txt) :
```
MatchingKey SubstValue
MatchingKey SubstValue # comment
```

FIX: add inline comment support in text rewrite map file

---

bin/catalina.bat
bin/service.bat

**Reference:** Commit 0c75cd1e3ac85944fb8ecbcf88cc38e9fa1fe4d5 by @markt-asf 
**Issue:** The commit referred did miss to keep `service.bat` JvmOptions9 in line with the change of catalina.bat made by that commit.
**Changes:**
- service.bat:
- fix JvmOptions9 to followup according changes in catalina.bat
- improve legibility of JvmOptions9 parameter line by introducing intermediate set variable JVM9_OPTIONS
- add comment to JVM9_OPTIONS settings with hint to keep in line with catalina.bat
- catalina.bat:
- add comment to JDK_JAVA_OPTIONS --add-opens settings with hint to keep in line with service.bat
**Test result: (updated after commit 3767fd5bdb1e09c19d42b499ff71b1c7e3e35436)**

[fix] service.bat JvmOptions9 - FollowUp on Improve CVE-2024-56337 protection

---

webapps/docs/cluster-howto.xml

This PR fixes a documentation inaccuracy in `cluster-howto.xml`.
The original text incorrectly states that static memberships are configured using `StaticMembershipInterceptor`.
However, the correct class to use in the `<Membership>` element is `StaticMembershipService`.
This fix updates the wording and clarifies the distinction between the two classes to avoid misleading users.
No runtime behavior is affected by this change — documentation only.
Bugzilla: https://bz.apache.org/bugzilla/show_bug.cgi?id=69747

Fix incorrect reference to StaticMembershipInterceptor in cluster-howto.xml

---

webapps/docs/introduction.xml

Fixed a typo in the Tomcat documentation where `CATALIA_HOME` was missing the letter 'N' and should be `CATALINA_HOME`.
- Changed `CATALIA_HOME` to `CATALINA_HOME` on line 118 of the introduction documentation
- This ensures consistency with the correct environment variable name used throughout Tomcat

Fix typo: Change CATALIA_HOME to CATALINA_HOME in documentation

---

java/org/apache/juli/JsonFormatter.java
java/org/apache/juli/OneLineFormatter.java

Description
---
This PR made the following two modifications
- Unify constant delimiters
- Refactoring for better readability
Explanation
---
**Unify constant delimiters**
Constants managed in the Constants class in the coyote package are separated by _ for better readability.
globalCacheSize -> GLOBAL_CACHE_SIZE
localCacheSize -> LOCAL_CACHE_SIZE
**Refactoring for better readability**
The OneLineFormatter class format() method contains thread logic. I think separating it into its own method would make the code easier to read. I also refactored the thread output into the JsonFormatter class, which extend from OneLineFormatter, by declaring it as protected.

refactor: formatter refactoring
