apache/tomcat

webapps/ROOT/index.jsp
Signed-off-by: samslow <shsvkdldj@likelion.org>
I don't know why this comments is here.
If there is a reason why the comment is here and I do not know, Abort this PR and Teach me if you can
=> Remove duplicated comments

java/org/apache/coyote/http11/Http11Processor.java
=> Fix typo for prefect

java/org/apache/tomcat/util/threads/LimitLatch.java
when i read `LimitLatch.java` I saw that obvious format error
=> Polish. Add spaces

java/org/apache/tomcat/util/http/CookieProcessorBase.java, java/org/apache/tomcat/util/http/LegacyCookieProcessor.java, java/org/apache/tomcat/util/http/LocalStrings.properties, java/org/apache/tomcat/util/http/Rfc6265CookieProcessor.java, java/org/apache/tomcat/util/http/SameSiteCookies.java, test/org/apache/tomcat/util/http/TestCookieProcessorGeneration.java, test/org/apache/tomcat/util/http/TestSameSiteCookies.java, webapps/docs/changelog.xml, webapps/docs/config/cookie-processor.xml
Add unset option to same-site cookies and pass through none value if set by user.
=> Fix https://bz.apache.org/bugzilla/show_bug.cgi?id=63865

modules/jdbc-pool/src/main/java/org/apache/tomcat/jdbc/naming/GenericNamingResourcesFactory.java
optimized code,replace some c-style array  Brackets are a part of an Array type. The definition could be: String[] args
=> optimized code,replace some c-style array

res/bnd/annotations-api.jar.tmp.bnd, res/bnd/build-defaults.bnd, res/bnd/catalina-ha.jar.tmp.bnd, res/bnd/catalina-ssi.jar.tmp.bnd, res/bnd/catalina-storeconfig.jar.tmp.bnd, res/bnd/catalina-tribes.jar.tmp.bnd, res/bnd/catalina.jar.tmp.bnd, res/bnd/el-api.jar.tmp.bnd, res/bnd/jasper-el.jar.tmp.bnd, res/bnd/jasper.jar.tmp.bnd, res/bnd/jaspic-api.jar.tmp.bnd, res/bnd/jsp-api.jar.tmp.bnd, res/bnd/servlet-api.jar.tmp.bnd, res/bnd/tomcat-api.jar.tmp.bnd, res/bnd/tomcat-coyote.jar.tmp.bnd, res/bnd/tomcat-dbcp.jar.tmp.bnd, res/bnd/tomcat-embed-core.jar.tmp.bnd, res/bnd/tomcat-embed-el.jar.tmp.bnd, res/bnd/tomcat-embed-jasper.jar.tmp.bnd, res/bnd/tomcat-embed-websocket.jar.tmp.bnd, res/bnd/tomcat-juli.jar.tmp.bnd, res/bnd/tomcat-util-scan.jar.tmp.bnd, res/bnd/tomcat-util.jar.tmp.bnd, res/bnd/tomcat-websocket.jar.tmp.bnd, res/bnd/websocket-api.jar.tmp.bnd, webapps/docs/changelog.xml
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> Store common build details in a shared build-defaults.bnd

build.properties.default, webapps/docs/changelog.xml
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> Fix BZ 64532 - update to bnd 5.1.1

build.xml, res/bnd/annotations-api.jar.tmp.bnd, res/bnd/build-defaults.bnd, res/bnd/catalina-tribes.jar.tmp.bnd, res/bnd/catalina.jar.tmp.bnd, res/bnd/el-api.jar.tmp.bnd, res/bnd/jasper-el.jar.tmp.bnd, res/bnd/jasper.jar.tmp.bnd, res/bnd/jaspic-api.jar.tmp.bnd, res/bnd/jsp-api.jar.tmp.bnd, res/bnd/servlet-api.jar.tmp.bnd, res/bnd/spec-defaults.bnd, res/bnd/tomcat-coyote.jar.tmp.bnd, res/bnd/tomcat-embed-core.jar.tmp.bnd, res/bnd/tomcat-embed-el.jar.tmp.bnd, res/bnd/tomcat-embed-jasper.jar.tmp.bnd, res/bnd/tomcat-embed-websocket.jar.tmp.bnd, res/bnd/tomcat-util.jar.tmp.bnd, res/bnd/tomcat-websocket.jar.tmp.bnd, res/bnd/websocket-api.jar.tmp.bnd, webapps/docs/changelog.xml
Requires a unique PR for 9.0.x branch
=> Fix bz64540

build.xml, webapps/docs/changelog.xml
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> Fix BZ 64544 - add built libs to the bnd classpath for introspection

.github/workflows/ci.yml, build.xml
Run github actions on branch pushes and PRs
Signed-off-by: Raymond Augé <rotty3000@apache.org>
=> github actions

README.md
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md034---bare-url-used
=> Fix bare URL

.travis.yml
Updated travis.yml to trigger build on ppc64le platform.
=> Added changes required for ppc64le support

java/org/apache/catalina/core/LocalStrings_ru.properties
Added Russian translate to LocalStrings_ru.properties for standardWrapper
=> Added Russian LocalStrings_ru.properties for standardWrapper

res/ide-support/eclipse/eclipse.classpath, res/ide-support/idea/tomcat.iml, res/ide-support/netbeans/project.xml
**Problem:**
I followed the steps [here](https://tomcat.apache.org/tomcat-10.0-doc/building.html) to build tomcat. I run the command `ant ide-intellij`, then open the IDEA. The package aQute will not be found.
**What I have done:**
Just modify the version of that package.
=> Update ide-support package version

java/org/apache/coyote/AbstractProtocol.java
Optimize if condition in `AbstractProtocol.startAsyncTimeout()`,
from `if (timeoutFuture == null || (timeoutFuture != null && timeoutFuture.isDone()))`
to `if (timeoutFuture == null || timeoutFuture.isDone())`
=> Optimize if condition

java/jakarta/servlet/ServletContext.java
I am reading the Servlet spec and I found a number mismatched.
What I have changed:
- Update a number from 4 to 5
=> update Servlet version in ServletContext.java

.editorconfig, CONTRIBUTING.md
see also: https://github.com/apache/tomcat/pull/282#pullrequestreview-399324287
=> Improve General IDE support

conf/catalina.properties
log4j-jakarta-web*.jar is the jar that supports Jakarta EE 9+ web servlet containers
=> Refer to correct log4j web jar

test/org/apache/catalina/valves/TestErrorReportValve.java
fix [BZ66206](https://bz.apache.org/bugzilla/show_bug.cgi?id=66206)
=> Bugfix for 66206 - TestErrorReportValve test is failing on a non-English PC

java/org/apache/catalina/connector/Response.java
HTTP2 also supports relative redirects.
=> Optimize comment

modules/stuffed/Dockerfile
In order to overcome the server.xml permission denial problem.
Signed-off: [vassilismourikis@gmail.com](mailto:vmouriki@redhat.com)
=> conf permissions in Dockerfile

java/org/apache/catalina/startup/VersionLoggerListener.java, java/org/apache/catalina/storeconfig/ConnectorStoreAppender.java, java/org/apache/catalina/storeconfig/StandardContextSF.java, java/org/apache/catalina/storeconfig/StoreContextAppender.java, java/org/apache/catalina/storeconfig/StoreFileMover.java, java/org/apache/tomcat/jni/Library.java, test/org/apache/catalina/startup/LoggingBaseTest.java, test/org/apache/tomcat/util/file/TestConfigFileLoader.java
Created a branch and PR because my local git shows some new class files and I'm not sure where they came from so doing it this way so that I can safely review the patch before merging it
=> Use available constants

java/org/apache/catalina/servlets/DefaultServlet.java
=> Bug 66618: add longDate attribute to XML in directory listing

webapps/docs/config/valve.xml
this change is with respect to issue #66662
=> Documentation change for Digest Authenticator Valve - spell corrected for attribute algorithm

webapps/docs/changelog.xml, webapps/docs/config/ajp.xml, webapps/docs/config/http.xml
Fixes https://bz.apache.org/bugzilla/show_bug.cgi?id=66686
=> Sync Configuration Reference with Connector's source code (10.1.x)

webapps/docs/changelog.xml, webapps/docs/config/ajp.xml, webapps/docs/config/http.xml
Fixes https://bz.apache.org/bugzilla/show_bug.cgi?id=66686
=> Sync Configuration Reference with Connector's source code (9.0.x)

webapps/docs/changelog.xml, webapps/docs/config/ajp.xml, webapps/docs/config/http.xml
Fixes https://bz.apache.org/bugzilla/show_bug.cgi?id=66686
=> Sync Configuration Reference with Connector's source code (8.5.x)

java/org/apache/coyote/Request.java
hello 😄 
I was looking at the code for the Request class in coyote.
Removed unnecessary brackets for consistency with the other code.
e.g. `contentLength = (clB == null || clB.isNull()) ? -1 : clB.getLong();`
=> Removed unnecessary brackets

java/org/apache/catalina/connector/ResponseFacade.java
https://github.com/apache/tomcat/pull/654#issuecomment-1706706294
This was discussed in the comments above!
=> Eliminating duplicate execution of checkFacade logic in ResponseFacade

java/org/apache/coyote/Request.java
Upon reviewing these changes, I've noticed a significant improvement in code readability. This enhanced readability stands out and will make a substantial difference in maintaining and debugging the code, as well as facilitating collaboration among developers.
I believe that this change elevates code quality and simplifies maintenance. By simplifying and making the code more straightforward, we can prevent errors and enhance code comprehensibility.
Once again, thank you for your contribution to this effort. If there are any additional improvements or if you need any further feedback, please feel free to let me know!
=> Simplify and enhance charset extraction from content type

test/org/apache/catalina/valves/rewrite/TestRewriteValve.java
This test adds code coverage for compatibility with rewrite from httpd for non existent headers
=> Tests the compatibility with rewrite from httpd for non existent headers

java/org/apache/catalina/servlets/WebdavServlet.java
Modify unused webdav status codes: 
* 418 is sc of a 1 April Rfc. (418 I'm a teapot).
* 422 (Unprocessable Content) Comply with [Rfc9110](https://httpwg.org/specs/rfc9110.html#changes.from.rfc.7231)
* SC_INSUFFICIENT_SPACE_ON_RESOURCE is same with SC_INSUFFICIENT_STORAGE semantically.
=> follow rfc spec: 422 - SC_UNPROCESSABLE_ENTITY, Abuse 418

test/jakarta/websocket/TesterContainerProviderPerformance.java
Fixing a typo in a class comment.
=> Tiny typo adjustment

test/jakarta/servlet/TestServletRequestParametersFormUrlEncoded.java, test/jakarta/servlet/TestServletRequestParametersMultipartEncoded.java
add CRLF after the last-chunk to build a valid chunked request body.
=> fix incomplete chunked request body in testcase

java/org/apache/tomcat/util/http/RequestUtil.java, test/org/apache/tomcat/util/http/TestRequestUtilSameOrigin.java
- simplify code and secure origin comparison in RequestUtil
=> clean up org.apache.tomcat.util.http  RequestUtil

java/org/apache/catalina/filters/CorsFilter.java
This PR refactors the checkRequestType method in the CORS filter to simplify and improve the readability of the request type determination logic. The main changes are:
+ Early Returns: The code has been simplified to return early for various conditions (e.g., invalid CORS requests, same-origin requests, missing or invalid headers). This reduces nesting and enhances readability.
+ Consolidation of Conditions: Some conditional blocks that check for empty or invalid headers were merged to avoid redundant checks, making the code more concise.
+ Improved Flow: The logic now more clearly distinguishes between the different CORS request types by handling the OPTIONS method, GET/HEAD methods, and POST method (with content type checks) in a more straightforward manner.
=> Refactor CORS Request Type Checking Logic for Simplicity and Clarity

java/org/apache/coyote/AsyncStateMachine.java, java/org/apache/tomcat/util/bcel/classfile/ConstantPool.java, webapps/docs/changelog.xml, webapps/docs/config/http.xml, webapps/docs/default-servlet.xml, webapps/docs/jndi-resources-howto.xml, webapps/docs/rewrite.xml, webapps/docs/ssl-howto.xml, webapps/docs/tomcat-docs.xsl
Docs clean ups in Java, XML and XSL
=> misc: fix grammar / spelling / remove duplicate words

java/org/apache/coyote/http2/Hpack.java, test/org/apache/coyote/http2/TestHpack.java
consider the possibility of integer overflow before result add.
=> BZ 69762 - integer overflow detection fixe enhance

test/org/apache/catalina/core/TestSwallowAbortedUploads.java
The test assumed write would fail once the server stopped swallowing, but  the client could finish buffering data before the close was observed, so no SocketException was thrown during the write and the assertion failed.
=> Stabilize TestSwallowAbortedUploads.testChunkedPUTLimit

webapps/docs/config/host.xml
https://github.com/apache/tomcat/blob/main/java/org/apache/catalina/startup/Constants.java#L37
=> typo: war-tracking -> war-tracker
